cache:
  paths:
    - baseconvert.com/node_modules/

stages:
  - build
  - deploy


build:
  image: node:6
  stage: build
  script:
    - cd baseconvert.com
    - npm install --only=dev --progress=false
    - node node_modules/.bin/grunt
  artifacts:
    expire_in: 1 week
    paths:
      - baseconvert.com/dist


deploy:
  image: alpine
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -avz ./baseconvert.com/dist/ "$DEPLOY_DESTINATION"
